### ISSUE TITLE
在用Java 11编译此项目时，报告了一个错误

### ISSUE THREAD

**Issue by tangqiu0205** [kotlin-orm/ktorm-kapt#3]
提示信息如下： 
Symbol is declared in module 'jdk.compiler' which does not export package 'com.sun.tools.javac.code'

Gradle中加入以下代码 也报同样问题
tasks.withType( JavaCompile ).configureEach {
    options.forkOptions.jvmArgs.addAll( ['--add-exports', 'jdk.compiler/com.sun.tools.javac.code=ALL-UNNAMED'] )
}

**Comment by vincentlauvlwj** [comment]
这个项目目前还没有内容，有什么好编译的呢...
